import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#92db0b",
        "primary-fixed": "#adf836",
        "primary-container": "#adf836",
        "on-primary-fixed-variant": "#324f00",
        "on-primary-fixed": "#111f00",
        "on-primary-container": "#486f00",
        "on-primary": "#213600",
        primary: "#ffffff",
        secondary: "#c4c7c9",
        "secondary-fixed": "#e0e3e5",
        "secondary-fixed-dim": "#c4c7c9",
        "secondary-container": "#464a4b",
        "on-secondary": "#2d3133",
        "on-secondary-container": "#b6b9bb",
        tertiary: "#ffffff",
        "tertiary-fixed": "#f1dbf8",
        "tertiary-fixed-dim": "#d4c0db",
        "tertiary-container": "#f1dbf8",
        background: "#101509",
        "on-background": "#e0e5d1",
        surface: "#101509",
        "surface-dim": "#101509",
        "surface-bright": "#363b2d",
        "surface-tint": "#92db0b",
        "surface-variant": "#323729",
        "surface-container": "#1c2115",
        "surface-container-low": "#181d11",
        "surface-container-lowest": "#0b1005",
        "surface-container-high": "#272c1f",
        "surface-container-highest": "#323729",
        "on-surface": "#e0e5d1",
        "on-surface-variant": "#c1caaf",
        "inverse-surface": "#e0e5d1",
        "inverse-on-surface": "#2d3225",
        "inverse-primary": "#436900",
        outline: "#8b947b",
        "outline-variant": "#424a35",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "accent-pink": "#FF2E63",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        unit: "4px",
        gutter: "16px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "display-lg": ["'Bebas Neue'", "sans-serif"],
        "display-md": ["'Bebas Neue'", "sans-serif"],
        "headline-lg": ["'Bebas Neue'", "sans-serif"],
        "headline-lg-mobile": ["'Bebas Neue'", "sans-serif"],
        "headline-md": ["'Bebas Neue'", "sans-serif"],
        "scoreboard-num": ["'Bebas Neue'", "sans-serif"],
        "label-caps": ["'Inter'", "sans-serif"],
        "body-lg": ["'Inter'", "sans-serif"],
        "body-md": ["'Inter'", "sans-serif"],
        "body-sm": ["'Inter'", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["80px", { lineHeight: "80px", letterSpacing: "0.02em", fontWeight: "400" }],
        "display-md": ["48px", { lineHeight: "48px", letterSpacing: "0.02em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "32px", letterSpacing: "0.04em", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "24px", letterSpacing: "0.04em", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "24px", letterSpacing: "0.05em", fontWeight: "400" }],
        "scoreboard-num": ["40px", { lineHeight: "40px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
